= Creating a content pipeline with Antora

This is a demo repository shows how to:

* Using Antora and its extensions to collects AsciiDoc content from Git and content-generating scripts.
* Publish the content on a website and use it also in other places like a PDF.

== This repository features

Main application:

https://antora.org/[Antora]::
The multi-repository documentation site generator for tech writers who ♥ writing in AsciiDoc.

The extensions:

https://gitlab.com/antora/antora-lunr-extension[Antora Lunr]:: Create a search index for the site which is built with JavaScript can be served from a static site with no additional backend.

https://gitlab.com/antora/antora-collector-extension[Antora Collector]:: Generate content from outside of Git and use it like any other content.
+
Go to xref:docs/content_v2/antora.yml[] to follow some bread crumbs how it has been configured.

https://gitlab.com/antora/antora-assembler[Antora Assembler]:: Take all pages of an Antora component
+
Go to xref:playbook/antora-assembler.yml[] to follow some bread crumbs how it has been configured.

== What's different from a real project

This is demo project some things are simplified which would be different in a real project:

* Documentation (the content) and Playbook (the representation) usually live in different Git repositories.
+
The documentation can even be split out to multiple Git repositories which would be combined with one playbook per published website.

* Different versions of the documentation live usually in different branches.
+
In this example the different versions are stored in different folders to allow for a simpler navigation.

* The playbook folder contains an author-style playbook which uses the local checked-out repository's worktree.
This is idea for a local exploration and experimentation.
+
In a production setup, the real playbook uses a URL for the Git repository and can build different content/versions and use different attributes.

== See the result

This project is being published via a GitHub action to a demo site.

Go to https://ahus1.github.io/antora-extensions-demo/ to see the result in your browser.

== Building

To build this project manually, see xref:.github/workflows/docs-pages.yml[] or xref:playbook/BUILDING.adoc[]

== Further reading

To find out more about Antora, see https://docs.antora.org/antora/latest/ for details.

As a project which uses Antora Collector and Antora Assembler, see the Eclipse Che Docs at https://github.com/eclipse-che/che-docs.

== Copyright and Licensing

Copyright (C) 2023-present Alexander Schwartz and the individual contributors.
Released under the Mozilla Public License Version 2.0 (see link:LICENSE[LICENSE]).
