name: Testing Documentation Site

on:
  pull_request:

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: 'playbook/package-lock.json'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: playbook
      - name: Build docs
        working-directory: playbook
        # language=shell
        env:
          BUNDLE_PATH: ''
        run: |
          npm install
          npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: playbook/_site/antora-extensions-demo
